version: '3'
services:
  database:
    image: mysql:latest
    container_name: sql_database
    volumes:
      - ./db/db-setup:/docker-entrypoint-initdb.d/:ro
      - ./db/data:/var/lib/mysql:rw
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootPassword123
  web:
    build: ./src
    ports:
      - "80:8080"
    volumes:
      - ./src/app:/usr/local/tomcat/webapps/bostoncc
    depends_on:
      - database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb1
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root